apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-component-pac-nsxlfn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-qdvw-tenant/build-suite-test-application-dwuc/test-component-pac-nsxlfn@sha256:0fadededc95b6ebd974690079fc05c68bc2002b3e8e86d63ae272445979eb7a7
        name: my-nginx
        resources: {}
status: {}
