apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-pac-nsxlfn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-pac-nsxlfn
    app.kubernetes.io/part-of: build-suite-test-application-dwuc
  name: test-component-pac-nsxlfn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-component-pac-nsxlfn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-component-pac-nsxlfn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-qdvw-tenant/build-suite-test-application-dwuc/test-component-pac-nsxlfn@sha256:0fadededc95b6ebd974690079fc05c68bc2002b3e8e86d63ae272445979eb7a7
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
